services:
  akmatov-e-m-netology-prometheus:
    image: prom/prometheus:latest
    container_name: akmatov-e-m-netology-prometheus
    ports:
      - "9090:9090"
    volumes: 
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - my_network

  akmatov-e-m-netology-pushgateway:
    image: prom/pushgateway:latest
    container_name: akmatov-e-m-netology-pushgateway
    ports:
      - "9091:9091"
    networks:
      my_network:
        aliases:
          - pushgateway

networks:
  my_network:
    name: Akmatov_E_M-my-netology-hw
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16

volumes:
  db_data: {}
  static_content: {}